### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by ramnathv** [trestletech/ShinyDash#17]
This looks really nice. I am working on a similar package, named `dashifyr` to provide a modular infrastructure for dashboards based on Shiny.

http://github.com/ramnathv/dashifyr

We should certainly talk at some point and exchange notes.

PS. Apologies for posting it as an issue here.

**Comment by trestletech** [comment]
Absolutely! Thanks for reaching out.

I'm hoping to have the Rickshaw integration in-place by the weekend, at which point I think it would definitely be wise to discuss the relationship between these two projects. Would you have time for a G+ Hangout next week? My email should be visible in my GitHub profile so we can schedule, if you'd like.
