### ISSUE TITLE
Problem running ShinyDash - could not find function "init"

### ISSUE THREAD

**Issue by midraed** [trestletech/ShinyDash#34]
Installed ShinyDash, also Shiny 0.6.0.99. Trying to run the example in my server with Shiny-server, so I copied ui.R and server.R from ShinyDash Example. 
But im getting ERROR: could not find function "init" when pointing to localhost:3838.

If i run ui.R in R im getting the same error, specifically when using function "gridster". As in :
gridster(tile.width = 250, tile.height = 250, ... ...

Do you have any tips?

**Comment by trestletech** [comment]
Hi. Sorry for the bug -- we had renamed a function and didn't catch that function call.

Can you try updating the package (`library(devtools); install_github("ShinyDash", "trestletech");` to see if that fixes it?

Thanks.

**Comment by midraed** [comment]
Excellent!!! Now works flawlessly.

**Comment by trestletech** [comment]
Great!
